startup_spread: 0

defaults:
    interval: 1m
    timeout: 45s
    attempts: 3
    critical_reminder_interval: 15m
imports:
    - nagios.yml
    - broken.yml

actions:
    - name: capture-json
      command: ./test_actions/capture-json.sh
      timeout: 5s
